import React from 'react';

const About = () => {
    return (
        <div className="animate-fade-in max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-12 text-gray-700">
            <section>
                <h1 className="text-4xl font-serif text-gray-900 mb-6">About Q-ADE Health</h1>
                <p className="text-lg leading-relaxed mb-4">
                    Q-ADE Health is dedicated to democratizing access to preliminary medical insights.
                    Powered by advanced Artificial Intelligence, our platform aims to bridge the gap between initial symptom onset and professional medical consultation.
                </p>
                <p className="text-lg leading-relaxed">
                    We believe that informed patients make better health decisions. By providing instant, evidence-based analysis of symptoms, we empower individuals to understand their health risks and seek appropriate care with confidence.
                </p>
            </section>

            <section className="bg-medical-teal/5 p-8 rounded-xl border border-medical-teal/10">
                <h2 className="text-2xl font-serif text-medical-teal mb-4">Our Technology</h2>
                <p className="leading-relaxed">
                    Our Symptom Checker utilizes Large Language Models (LLMs) trained on vast medical datasets.
                    It analyzes natural language inputs to identify potential conditions, assess risk levels, and suggest actionable next steps.
                    It is designed to be intuitive, fast, and accessible 24/7.
                </p>
            </section>

            <section className="border-l-4 border-yellow-500 pl-6 py-2">
                <h2 className="text-xl font-bold text-gray-900 mb-2">Medical Disclaimer</h2>
                <p className="text-sm text-gray-600 leading-relaxed italic">
                    Q-ADE Health is an information tool and does <strong>not</strong> provide medical advice, diagnosis, or treatment.
                    The information generated by this AI is for educational and informational purposes only.
                    Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.
                    <strong>If you think you may have a medical emergency, call your doctor or emergency services immediately.</strong>
                </p>
            </section>
        </div>
    );
};

export default About;
